

const TERMS = [
    { label: 'V', full: 'Volume', desc: 'Total monthly trading volume in USD generated by the partner.' },
    { label: 'F', full: 'Blended Fee', desc: 'Average trading fee rate (e.g., 0.035%) across all user tiers.' },
    { label: 'P', full: 'Partner Share', desc: 'Percentage of the total fee pool allocated to the Agency/Partner.' },
    { label: 'S', full: 'Sub-split (KOL Share)', desc: 'Procent z Partner Share przekazywany bezpośrednio do KOL/Creatora (np. 30% z zysku partnera).' },
    { label: 'R', full: 'Retainer', desc: 'Fixed monthly payment (USD) paid to the partner regardless of volume.' },
    { label: 'I', full: 'Integration/Op Cost', desc: 'One-time or monthly operational costs for technical setup.' },
    { label: 'B', full: 'Bonus', desc: 'Additional cash incentive paid for every $1M of trading volume.' },
];

export function Glossary() {
    return (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
            {TERMS.map(t => (
                <div key={t.label} style={{
                    display: 'grid',
                    gridTemplateColumns: '30px 1fr',
                    gap: '12px',
                    paddingBottom: '8px',
                    borderBottom: '1px solid rgba(255,255,255,0.04)'
                }}>
                    <div style={{
                        fontWeight: 900,
                        color: 'var(--accent-blue)',
                        fontSize: '0.9rem',
                        textAlign: 'center'
                    }}>
                        {t.label}
                    </div>
                    <div>
                        <div style={{ fontSize: '0.75rem', fontWeight: 700, color: 'rgba(255,255,255,0.8)' }}>
                            {t.full}
                        </div>
                        <div style={{ fontSize: '0.65rem', color: 'rgba(255,255,255,0.4)', lineHeight: 1.3, marginTop: '2px' }}>
                            {t.desc}
                        </div>
                    </div>
                </div>
            ))}
            <div style={{
                marginTop: '4px',
                fontSize: '0.6rem',
                color: 'var(--accent-cyan)',
                fontStyle: 'italic',
                opacity: 0.6
            }}>
                Hover over values in the terminal for quick definitions.
            </div>
        </div>
    );
}

export const TOOLTIPS = {
    V: "Monthly Trading Volume (USD)",
    F: "Blended Trading Fee (%)",
    P: "Partner/Agency Fee Share (%)",
    S: "KOL/Creator Sub-split (%) - share of partner revenue",
    R: "Fixed Monthly Retainer (USD)",
    I: "Operational/Integration Cost (USD)",
    B: "Bonus per $1M Volume (USD)",
    margin: "Safety buffer after all payouts and costs."
};
